version: '3.8'
services:
  mkdocs:
    build: .
    context: ..
    dockerfile: local/Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ..:/workspace:cached
    environment:
      - PYTHONUNBUFFERED=1
